# Generated by Django 4.2.7 on 2025-12-19 05:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gst_number', models.CharField(max_length=15, unique=True, verbose_name='GST Number')),
                ('contact_info', models.TextField(blank=True, verbose_name='Contact Information')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Current Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_type', models.CharField(choices=[('ADVANCE_RECEIVED', 'Advance Received'), ('REFUND_GIVEN', 'Refund Given')], max_length=20, verbose_name='Transaction Type')),
                ('date', models.DateField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='transaction_evidence/', verbose_name='Evidence (Bank Screenshot)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tracker.partner')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_type', models.CharField(choices=[('ADVANCE_RECEIVED', 'Advance Received'), ('REFUND_GIVEN', 'Refund Given')], max_length=20, verbose_name='Transaction Type')),
                ('date', models.DateField()),
                ('evidence_file', models.TextField(blank=True, max_length=100, null=True, verbose_name='Evidence (Bank Screenshot)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracker.partner')),
            ],
            options={
                'verbose_name': 'historical transaction',
                'verbose_name_plural': 'historical transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPartner',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gst_number', models.CharField(db_index=True, max_length=15, verbose_name='GST Number')),
                ('contact_info', models.TextField(blank=True, verbose_name='Contact Information')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Current Balance')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical partner',
                'verbose_name_plural': 'historical partners',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300, verbose_name='Item Name')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Estimated Cost')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Actual Cost')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Commission %')),
                ('vendor_invoice', models.TextField(blank=True, max_length=100, null=True, verbose_name='Vendor Invoice')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='End Client Name')),
                ('tracking_id', models.CharField(blank=True, max_length=100, verbose_name='Tracking ID')),
                ('courier_partner', models.CharField(blank=True, max_length=100, verbose_name='Courier Partner')),
                ('status', models.CharField(choices=[('SOURCING', 'Sourcing'), ('BOOKED', 'Booked'), ('IN_WAREHOUSE', 'In Warehouse'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned')], default='SOURCING', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('cost_deducted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracker.partner')),
            ],
            options={
                'verbose_name': 'historical deal',
                'verbose_name_plural': 'historical deals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300, verbose_name='Item Name')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Estimated Cost')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Actual Cost')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Commission %')),
                ('vendor_invoice', models.FileField(blank=True, null=True, upload_to='vendor_invoices/', verbose_name='Vendor Invoice')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='End Client Name')),
                ('tracking_id', models.CharField(blank=True, max_length=100, verbose_name='Tracking ID')),
                ('courier_partner', models.CharField(blank=True, max_length=100, verbose_name='Courier Partner')),
                ('status', models.CharField(choices=[('SOURCING', 'Sourcing'), ('BOOKED', 'Booked'), ('IN_WAREHOUSE', 'In Warehouse'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned')], default='SOURCING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_deducted', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='tracker.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
