# Generated by Django 6.0 on 2025-12-19 09:21

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone as tz


def generate_unique_references(apps, schema_editor):
    """Generate unique reference numbers for all existing deals."""
    Deal = apps.get_model('tracker', 'Deal')
    for deal in Deal.objects.all():
        date_str = tz.now().strftime('%Y%m%d')
        deal.reference = f"DEAL-{date_str}-{uuid.uuid4().hex[:4].upper()}"
        deal.save(update_fields=['reference'])


def generate_unique_references_history(apps, schema_editor):
    """Generate unique reference numbers for all existing historical deals."""
    HistoricalDeal = apps.get_model('tracker', 'HistoricalDeal')
    for deal in HistoricalDeal.objects.all():
        date_str = tz.now().strftime('%Y%m%d')
        deal.reference = f"DEAL-{date_str}-{uuid.uuid4().hex[:4].upper()}"
        deal.save(update_fields=['reference'])


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add reference field without unique constraint
        migrations.AddField(
            model_name='deal',
            name='reference',
            field=models.CharField(default='', editable=False, max_length=20, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='reference',
            field=models.CharField(db_index=True, default='', editable=False, max_length=20, verbose_name='Reference'),
        ),
        
        # Step 2: Generate unique references for existing records
        migrations.RunPython(generate_unique_references, migrations.RunPython.noop),
        migrations.RunPython(generate_unique_references_history, migrations.RunPython.noop),
        
        # Step 3: Make the field unique
        migrations.AlterField(
            model_name='deal',
            name='reference',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Reference'),
        ),
        
        # Other model changes
        migrations.AlterField(
            model_name='deal',
            name='item_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='historicaldeal',
            name='item_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Item Name'),
        ),
        migrations.CreateModel(
            name='DealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300, verbose_name='Item Name')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Item Price (per unit)')),
                ('commission_per_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Commission per Item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tracker.deal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDealItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300, verbose_name='Item Name')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Item Price (per unit)')),
                ('commission_per_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Commission per Item')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracker.deal')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical deal item',
                'verbose_name_plural': 'historical deal items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
